# drawsvg.pyi: type hints for drawsvg

from typing import Any, Optional

class Drawing:
    width: float
    height: float
    def __init__(
        self,
        width: float,
        height: float,
        origin: tuple[float, float] = ...,
        context: Optional[Any] = ...,
        **kwargs: Any
    ) -> None: ...
    def append(self, element: Any) -> None: ...
    def save_svg(self, fname: str) -> None: ...
    def save_png(self, fname: str) -> None: ...
    def as_svg(self) -> str: ...
    def rasterize(self) -> Any: ...

class DrawingElement:
    def __init__(self, **kwargs: Any) -> None: ...

class Rectangle(DrawingElement):
    def __init__(
        self, x: float, y: float, width: float, height: float, **kwargs: Any
    ) -> None: ...

class Circle(DrawingElement):
    def __init__(self, cx: float, cy: float, r: float, **kwargs: Any) -> None: ...

class Line(DrawingElement):
    def __init__(
        self, sx: float, sy: float, ex: float, ey: float, **kwargs: Any
    ) -> None: ...

class Path(DrawingElement):
    def __init__(self, **kwargs: Any) -> None: ...
    def M(self, x: float, y: float) -> Path: ...
    def L(self, x: float, y: float) -> Path: ...
    def H(self, x: float) -> Path: ...
    def V(self, y: float) -> Path: ...
    def Z(self) -> Path: ...

class Text(DrawingElement):
    def __init__(
        self, text: str, fontSize: float, x: float, y: float, **kwargs: Any
    ) -> None: ...

class Group(DrawingElement):
    def __init__(self, **kwargs: Any) -> None: ...
    def append(self, element: DrawingElement) -> None: ...
    def draw(self, obj: DrawingElement, **kwargs: Any) -> None: ...

# Add other elements as you need them
